#
# This is not the makefile to compile the source!
#
# Run the 'opp_makemake' command in this directory
# to get a makefile that compiles the source.
#

.PHONY: doc
doc:
	doxygen Doxyfile

.PHONY: tar
tar:
	git archive --format=tar master | gzip > ../hardwareclock_`date '+%Y-%m-%d_%H_%M'`.tar.gz
